stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: build-jekyll:$CI_COMMIT_REF_SLUG

build:
  stage: build
  image: docker:latest
  before_script:
    - docker info
  script:
    - echo $DOCKER_IMAGE
    - docker build -t $DOCKER_IMAGE .
    - docker run --rm -v $(pwd):/repo -v $(pwd)/output:/usr/share/out $DOCKER_IMAGE
  artifacts:
    paths:
      - output/

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - git config --global user.email "maxmob04@gmail.com"
    - git config --global user.name "britmob"
    - REPO_URL=$(echo $CI_REPOSITORY_URL | sed 's|http://||')
    - git clone --branch static-site --depth 1 https://oauth2:${CI_JOB_TOKEN}@${REPO_URL} static-site
    - cp -r output/* static-site/
    - cd static-site
    - git add .
    - git commit -m "Update static site [ci skip]"
    - git push https://oauth2:${CI_JOB_TOKEN}@${REPO_URL} static-site
  only:
    - main
