user root;
worker_processes  1;
daemon off;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;
    log_format main '$remote_addr - $remote_user [$time_local] [$msec] '
                    '[$request_time] "$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent" REAL IP: "$http_x_forwarded_for"';
    server {
        listen 80;
        server_name maxmob.sh;

        root /app/jekyll/_site;

        index index.html;

        access_log /nginx/access.log main;

        location / {
            try_files $uri $uri.html $uri/ =404;
        }

        location /static/resume.pdf {
            return 301 https://maxmob.sh/static/MaxMobleyResume.pdf;
        }

        location /static/ {
            alias /app/static/;
        }
    }

    server {
        listen 81;
        server_name resume.maxmob.sh;

        location / {
            return 301 https://maxmob.sh/static/MaxMobleyResume.pdf;
        }
    }
}
